spring:
  profiles:
  #激活开发环境
    active: dev
  #配置模板引擎
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    #数据库
    servlet:
      content-type: text/html

mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.zah.entity
